### ISSUE TITLE
FXMLView as custom control for Scene Builder 2

### ISSUE THREAD

**Issue by aliebelt** [AdamBien/afterburner.fx#29]
Hi Adam,
another week, another idea ;)

This week we try to use the "import custom control from JAR" feature of Scene Builder 2.
This works for e.g. the ControlsFX controls. But it's not possible for an afterburner.fx module .
Scene Builder scans all class-files in a selected jar, and checks if it is a sub-class of Node (e.g. Node, Parent or AnchorPane) and if no Exception is thrown when invoking the default-constructor. This feature is stil a little bit buggy, but basically very useful.

The following afterburner.fx-module "wrapper" works but can't be imported via JAR-Importer in Scene Builder 2.0 due to a Bug in Scene Builder:
```
public class TimeChartControl extends AnchorPane {

	TimeChartControlView view;

	public TimeChartControl() {
		view = new TimeChartControlView();
		AnchorPane.setBottomAnchor(view.getView(), 0.0);
		AnchorPane.setLeftAnchor(view.getView(), 0.0);
		AnchorPane.setRightAnchor(view.getView(), 0.0);
		AnchorPane.setTopAnchor(view.getView(), 0.0);
		getChildren().setAll(view.getView());
	}

	public TimeChartControlPresenter getPresenter() {
		return (TimeChartControlPresenter) view.getPresenter();
	}
}
```
This wrapper can be used as custom control in any fxml:
```
<?xml version="1.0" encoding="UTF-8"?>

<?import de.fhg.iwes.javafx.vpp.frontend.module.timechartcontrol.*?>
<?import javafx.scene.layout.*?>
<?scenebuilder-stylesheet powerplantdetails.css?>

<AnchorPane maxHeight="-1.0" maxWidth="-1.0" minHeight="-1.0" minWidth="-1.0" prefHeight="-1.0" prefWidth="-1.0" xmlns:fx="http://javafx.com/fxml/1"
	xmlns="http://javafx.com/javafx/2.2" fx:controller="de.fhg.iwes.javafx.vpp.frontend.module.details.powerplantdetails.PowerPlantDetailsPresenter">
	<children>
		<TimeChartControl fx:id="timeChartControl" />
	</children>
</AnchorPane>
```
Scene Builder stil opens the fxml but shows a little warning at the custom control (TimeChartControl in my case). I think this will be solved in a new Scene Builder version.
In the application the custom control is loaded properly.

Now my idea:
Actually the wrapper which I implemented is basically the FXMLView and also the view in the meaning of MVP. The difference is that FXMLView does not is the view but provides the view (via getView).
So what do you think about making FXMLView to the view instead of using it as a view-provider?
FXMLView could extend e.g. AnchorPane like in my example. The getView method could stil return the root-Node of the loaded fxml. So there is no API-break.
The result will be, that everybody will be able to include afterburner.fx-module-views as a custom control in fxml without using a wrapper.

**Comment by MichK21** [comment]
Good Morning, Gentlemen, I am just wondering what's the status of this? Is this feature going to make it's way in??

M.

**Comment by aliebelt** [comment]
Hi M., I don't know what Adam is thinking about it. I'm still very interested in this feature. But maybe someone (like you or me) can create a pull request... Best regards

**Comment by AdamBien** [comment]
If two users asks about that it seems important enough. I'm implementing a few afterburner features anyway right now. 

Summary: FXMLView should inherit from a Node and be not just a Node factory, right?

**Comment by AdamBien** [comment]
@aliebelt -> have you seen airfield?: http://www.adam-bien.com/roller/abien/entry/application_deployer_released_airfield_v0

**Comment by aliebelt** [comment]
Hi Adam, exactly. Basically it should be enough if FXMLView inherits from Node. But we have allready implemented some of these FXMLView-Wrappers mentioned in the issue description. 
We have come to the conclusion to only use AnchorPane as parent-class with 0.0 anchors on all sides. That has the advantage that the content of the FXMLView sticks to the border of the grafical module. If the module is than resized there where it is used, than the content of the module is resized too.

So my suggestion would be to have something like this: MyModule extends FXMLView extends AnchorPane

If there are problems importing a module into Scene Builder you can have a look into https://bitbucket.org/controlsfx/controlsfx/issues/243/all-controls-should-be-supported-by#comment-13039299

I've not seen airfield yet, looks very promising!

**Comment by jasons2000** [comment]
Hi all, is there any progress on this? I want to be able to use an Afterburner module as a component in FXML without having to write any wrappers.

Also, and perhaps this is related, but if I have component which happens to have no FXML, ie its very small and purely dynamic, how would I make an Afterburner module from this so that I can benefit from the Afterburner injection process.

**Comment by aliebelt** [comment]
An addition to my comment above: Using a StackPane as parent class for FXMLView is much easier than my previously suggestion (AnchorPane). StackPane resizes it's content to it's borders automatically.

**Comment by jasons2000** [comment]
Hi Andreas , I tried your original suggestion with the wrapper but it didn't appear to work for me. Is it possible to put a complete example together. Demonstrating the View , Presenter, Control and the FXML?

**Comment by jasons2000** [comment]
I should add that I'm using the topgun branch, as I already use google guice as my dependency injection  framework.

**Comment by jasons2000** [comment]
FYI, @aliebelt, I got your technique working with a StackPane, not sure what I was doing wrong before.

**Comment by aliebelt** [comment]
@jasons2000 that's great! The problem is, that there is no complete documentation out there which describes how to make a custom control working with Scene Builder (https://bugs.openjdk.java.net/browse/JDK-8091246).

**Comment by AdamBien** [comment]
FXMLView implements StackPane -- as suggested. I'm closing this issue now. If you are not satisfied, please reopen it. You will find the modification in 1.6.3-SNAPSHOT. All my tests are working so far.

**Comment by aliebelt** [comment]
Hi Adam, that are very good news.
I have seen that `FXMLView extends StackPane`, but there is no implementation which fill's the content of the StackPane with the view content (`getChildren().add(getView())`).
To use a custom control in Scene Builder it must be completely build by only using the default constructor. I think that is a little bit incompatible with the current FXMLView implementation where the default constructor says "Constructs the view lazily (fxml is not loaded) with empty injection context.".
I will try to investigate this point and make a suggestion next week.

**Comment by aliebelt** [comment]
@AdamBien can you please reopen this issue, I have no permission to do this.

**Comment by aliebelt** [comment]
At the moment I can see only one clean and meaningful solution:

The default constructor has to be changed to -non lazy initialization- and an additional constructor parameter could be added. Here is an example for a possible implementation:
```
public abstract class FXMLView extends StackPane {

...

	/**
	 * Constructs the view.
	 */
	public FXMLView() {
		this(f -> null, false);
	}

	/**
	 * @param injectionContext
	 *            the function is used as a injection source. Values matching for the keys are going to be used for injection into the corresponding presenter.
	 *            <br>
	 *            null is permitted and will result in same behavior as the the default constructor.
	 * @param lazyInitialization
	 *            If true the view will be loaded on demand by invoking e.g. {@link #getView()}. If false (default behavior) the view will be loaded directly
	 *            and put into this {@link FXMLView} (for use e.g. as custom control in Scene Builder).
	 */
	public FXMLView(Function<String, Object> injectionContext, boolean lazyInitialization) {
		this.injectionContext = injectionContext;
		this.init(getClass(), getFXMLName(), lazyInitialization);
	}

	private void init(Class clazz, final String conventionalName, boolean lazyInitialization) {
		this.presenterProperty = new SimpleObjectProperty<>();
		this.resource = clazz.getResource(conventionalName);
		this.bundleName = getBundleName();
		this.bundle = getResourceBundle(bundleName);
		if (!lazyInitialization) {
			getChildren().add(getView());
		}
	}

...

```

@AdamBien  What do you think?

**Comment by amrtn** [comment]
Following @aliebelt suggestion, I created a new FXMLView version to be used by custom controls

```java
package xxxx.gui.afterburner.views;

import java.util.function.Function;
import javafx.beans.property.SimpleObjectProperty;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author 
 */
public abstract class FXMLComponentView extends FXMLView {

  protected final Logger logger = LogManager.getLogger(getClass().getName());

  /**
   * Constructs the view lazily (fxml is not loaded) with empty injection context.
   */
  public FXMLComponentView() {
    this(f -> null, false);
  }

  //<editor-fold defaultstate="collapsed" desc="Support for SceneBuilder custom components">
  /**
   * Constructor to support the loading of custom components in Scene Builder
   *
   * @See https://github.com/AdamBien/afterburner.fx/issues/29#issuecomment-187073648
   *
   * @param injectionContext the function is used as a injection source. Values matching for the
   * keys are going to be used for injection into the corresponding presenter.
   * <br>
   * null is permitted and will result in same behavior as the the default constructor.
   * @param lazyInitialization If true the view will be loaded on demand by invoking e.g.
   * {@link #getView()}. If false (default behavior) the view will be loaded directly and put into
   * this {@link FXMLView} (for use e.g. as custom control in Scene Builder).
   */
  public FXMLComponentView(Function<String, Object> injectionContext, boolean lazyInitialization) {
    this.injectionContext = injectionContext;
    this.init(getFXMLName(), lazyInitialization);
  }

  private void init(final String conventionalName, boolean lazyInitialization) {
    try {
      this.presenterProperty = new SimpleObjectProperty<>();
      this.resource = getClass().getResource(conventionalName);
      this.bundleName = getBundleName();
      this.bundle = getResourceBundle(bundleName);
      if (!lazyInitialization) {
        getChildren().add(getView());
      }
    } catch (Exception e) {
      logger.log(Level.ERROR, String.format("Fatal error: %s", e.getMessage()), e);
      System.out.println(String.format("Fatal error: %s", e.getMessage()));
    }
  }
//</editor-fold>

}
```

Then your component can be instantiated like this: 

```java
public class RichDataTableView<T> extends FXMLComponentView {

  public RichDataTableView() {
  }
  
  public RichDataTablePresenter<T> getRealPresenter() {
    return (RichDataTablePresenter<T>) super.getPresenter();
  }

}
```
So far it's working great and there is no need to change the afterburner.fx core classes.
