### ISSUE TITLE
Problem load resource inside presenter instance

### ISSUE THREAD

**Issue by orzoweitop** [AdamBien/afterburner.fx#39]
UPDATE: I fix error, is not related with afterburner.fx. Solution is in StackOverflow question below.

I try to load a resource from an Injected object, exactly I try to load an image from resources folder into Presenter instance using getClass().getResourceAsStream() method, but always get null pointer exceptions.

Also, I tried but not works:

```java
imgLogo.setImage(new Image(Injector.instantiatePresenter(LoginPresenter.class).getClass().getResourceAsStream("/img/logo.png")));
```
</addr>

Note: I also create a question in StackOverflow about this question (https://stackoverflow.com/questions/27132257/afterburner-fx-fail-load-resource-from-object-injected)

**Comment by AdamBien** [comment]
Look at the project template: [http://www.adam-bien.com/roller/abien/entry/igniter_fx_the_afterburner_fx](http://www.adam-bien.com/roller/abien/entry/igniter_fx_the_afterburner_fx) Maven already loads e.g. fxml from custom folders. You "only" have to add your resources to the configuration.
