### ISSUE TITLE
Afterburner Git Organisation

### ISSUE THREAD

**Issue by rajmahendra** [AdamBien/afterburner.fx#41]
Nice idea of community should have a Organisation... its a good idea to move this to a Git Organisation so its easy to manage and maintain the project.

**Comment by AdamBien** [comment]
If afterburner were a commercial project, I would create an organization for it. What do you miss? You can freely clone the wiki, source code and make your own "afterburner" :-)

**Comment by rajmahendra** [comment]
:)
