### ISSUE TITLE
Community discussion group

### ISSUE THREAD

**Issue by rajmahendra** [AdamBien/afterburner.fx#42]
Its good to have a community discussion group (may be google group) where many things can be discussed...

**Comment by AdamBien** [comment]
My inbox-zero strategy barely works right now. However: use the issue tracker, twitter or Wiki. I try to keep afterburner as easy as only possible. Actually there are only three classes right now -- hopefully the purpose is self evident. If you like, feel free to ask questions at [http://airhacks.tv](http://airhacks.tv)
