### ISSUE TITLE
Make getConventionalName() protected

### ISSUE THREAD

**Issue by JanGerritsen** [AdamBien/afterburner.fx#43]
Hi I very much like your little framework, it makes developing JavaFX a lot of fun :), but one issue I have at the moment is your convention of naming the fxml files. 
I do not like the “all-lowercase” naming.  It makes some longer names very hard to read. So I would like to change it to allow CamelCaseNames by sub-classing FXMLView, but the getConventionalName() method is currently package protected and there is no other way to hook into the name resolution process.

**Comment by AdamBien** [comment]
Thanks, I'm glad you like afterburner.. getConventionalName is now protected. Sorry for the late reaction--but I had no leisure in the last weeks :-)
