### ISSUE TITLE
Controller / Presenter injection as convention?

### ISSUE THREAD

**Issue by benneq** [AdamBien/afterburner.fx#49]
I don't like to have the fully qualified name of the Presenter within the fxml file.

How about letting the FXMLView set the Controller / Presenter automatically?

```
foo.fxml
FooView.java
FooPresenter.java
```

That would make moving / renaming much easier.

**Comment by MewesK** [comment]
That's what DataFX is doing which results in losing proper IDE support. Is it really worth it?

**Comment by benneq** [comment]
I'm using Eclipse and E(fx)clipse. What do you mean with proper IDE support? The only thing it can do with JavaFX is opening fxml Files with SceneBuilder I guess.

**Comment by MewesK** [comment]
In Intellij IDEA you get support for controller fields and methods. It tells you if something is missing in your controller or can even auto-create fields and method stubs based on your fxml changes. Same with fxml/css. Never tried Eclipse though - I'm a huge Jetbrains fan boy.

**Comment by AdamBien** [comment]
But: right now the presenter is loaded by the FXML-runtime. Are you suggesting to load the presenter within the FXML view?

**Comment by AdamBien** [comment]
v1.7.0 comes with pluggable DI -- you can plug your own DI conventions now: http://www.adam-bien.com/roller/abien/entry/afterburner_fx_v1_7_0
