### ISSUE TITLE
getConventionalName with Locale = tr and classes / fxml containing 'i'

### ISSUE THREAD

**Issue by marcmai** [AdamBien/afterburner.fx#52]
When changing the default locale of a vm, a JavaFX-AfterburnerFX powered application is running in, the Method "protected String getConventionalName()" within FXMLView uses String clazz = this.getClass().getSimpleName().toLowerCase();

For example: If the name of the class starts with 'i' - let's say iHelp -  and the locale is changed to Turkish (tr), then 'toLowerCase()' returns ıHelp => Turkish 'ı' and not 'i'.
A fix could be to use  toLowerCase(Locale.ENGLISH); or to give a possibility to specify the Locale, the class- and file-names are written in.

(Some background info taken from java.lang.String.toLowerCase(Locale locale) docu:
Examples of lowercase mappings are in the following table: Language Code of Locale Upper Case Lower Case Description tr (Turkish) \u0130 \u0069 capital letter I with dot above -> small letter i tr (Turkish) \u0049 \u0131 capital letter I -> small letter dotless i (all) French Fries french fries lowercased all chars in String (all) lowercased all chars in String )

**Comment by Naoghuman** [comment]
Adding the functionality to define a Locale localeToLowerCase needs only a new **Constructor** where it is possible to define the Locale because the internal methods `getBundleName()`, `getStyleSheetName()` and `getFXMName()` used the method `getConventionalName(...)`.

The existing methods `getConventionalName(...)` need only extended with a new **internal** method where the Locale is used. So the definition from the Locale is done over the Constructor and the syncronisation from bundleName, styleSheetName, fxmlName and conventionName is okay.

**Comment by SimY4** [comment]
Would it be more logical to set `Locale.getDefault()` as default Locale insted of `Locale.ENGLISH`?

**Comment by marcmai** [comment]
I thing @Naoghuman's proposal could be a good one. So in case of internationalization one could set the locale all filenames are created with (in my case English).

@SimY4 : The default locale from the JVM is currently used. In my application I set the default locale on startup to be for example Turkish to have ResourceBundle pull the right language files. But then, also getConventionalName(...) behaves like described above.

@AdamBien : What do you think about this issue?

**Comment by AdamBien** [comment]
@Marcmal + all. I think we should use the Locale.getDefault() which is already used by the JVM. You could set the locale of your choice in th main() method. Wouldn't it be the best solution?

**Comment by Naoghuman** [comment]
I think also that the Locale.getDefault() should be used. This is the most normal used behavior in most applications. So like from @AdamBien suggested I changed to Local.Default().

_The behaivor is now:_
* Use a Constructor without the parameter Locale localeToLowerCase will use the predefined variable localeToLowerCase which is now Locale.getDefault().
* Setting a new Locale over a Contructor override the predefined variable localeToLowerCase.

_Constructors **without** the parameter localeToLowerCase:_
```java
/**
 * Constructs the view lazily (fxml is not loaded) with empty injection
 * context and {@link java.util.Locale#getDefault()} for the name converting.
 */
public FXMLView() {
    this(Locale.getDefault());
}

/**
 * Constructs the view lazily (fxml is not loaded) and {@link java.util.Locale#getDefault()} 
 * for the name converting.
 *
 * @param injectionContext the function is used as a injection source.
 * Values matching for the keys are going to be used for injection into the
 * corresponding presenter.
 */
public FXMLView(Function<String, Object> injectionContext) {
    this(injectionContext, Locale.getDefault());
}
```

_Constructors **with** the parameter localeToLowerCase:_
```java
/**
 * Constructs the view lazily (fxml is not loaded) with empty injection
 * context.
 * 
 * @param localeToLowerCase The locale for the name converting.
 */
public FXMLView(Locale localeToLowerCase) {
    this(f -> null, localeToLowerCase);
}

/**
 * Constructs the view lazily (fxml is not loaded).
 * 
 * @param injectionContext the function is used as a injection source.
 * Values matching for the keys are going to be used for injection into the
 * corresponding presenter.
 * @param localeToLowerCase The locale for the name converting.
 */
public FXMLView(Function<String, Object> injectionContext, Locale localeToLowerCase) {
    this.injectionContext = injectionContext;
    this.localeToLowerCase = localeToLowerCase;
        
    this.init(getFXMLName());
}
```

Internal leads the methods `getBundleName(): String`, `getStyleSheetName(): String`, `getFXMName(): String`, `getConventionalName(boolean lowercase, String ending): String` and `getConventionalName(boolean lowercase): String` to the **new** method `getConventionalName(boolean lowercase, Locale locale): String` where the variable localeToLowerCase (which is Locale.getDefault() or when overriden the user Locale) will used.

**Comment by AdamBien** [comment]
Solution: change the default Locale within the application's main method.

**Comment by marcmai** [comment]
I really would prefer the solution proposed by @Naoghuman, where it is possible to manually overwrite the default locale of the JVM only for the FXML resource loading. 

In our application, we use ResourceBundles for internationalization. If a user's locale is turkish (tr), ResourceBundle delivers the correct i18n resources for our display. If we would overwrite the Locale for the JVM with Locale.setDefault(...), the i18n-mechanism wouldn't work anymore.

I agree, that using Locale.getDefault() should be the standard behaviour. But adding an alternative constructor to overwrite this seems to me as a good way to adopt the behaviour to the applications needs.
