### ISSUE TITLE
Change PARENT_EXECUTOR_POOL's type to ExecutorService

### ISSUE THREAD

**Issue by RAnders00** [AdamBien/afterburner.fx#56]
I am talking about the `Executor` used by the `FXMLView`.

`Executor` is a very limited interface, and since a `ExecutorService` is returned by the `Executors.newCachedThreadPool(...)` anyways, we could use `ExecutorService`, which would then offer more functionality. This also does not break any existing programs, since `ExecutorService` is a supertype of `Executor`.

**Comment by AdamBien** [comment]
A good suggestion, implemented. Is part of the daily builds. Thanks!
