### ISSUE TITLE
Topgun 1.6.3 Release

### ISSUE THREAD

**Issue by jasons2000** [AdamBien/afterburner.fx#57]
Hi Adam, will you be doing a 1.6.3 release to maven central  for the topgun branch?

**Comment by AdamBien** [comment]
I looked at that. Merging is going to be a mess. However: I'm working on 1.7.0. I guess this release will kill topgun. Please stay tuned. However if you really like, merge the 1.6.3 topgun, create a pull request and I will release it.

**Comment by jasons2000** [comment]
I can keep using topgun1.6.2 for the time being, but look forward to the 1.7.0 release.

**Comment by AdamBien** [comment]
v1.7.0 is out and the DI is pluggable right now. I hope you like the solution.

**Comment by jasons2000** [comment]
Much appreciated, hopefully I can convert over to 1.7 by tomorrow

------ Original Message ------

**Comment by jasons2000** [comment]
Ok, one thing, based upon my reading of http://www.adam-bien.com/roller/abien/entry/afterburner_fx_v1_7_0. We are now expected to create  a META-INF/services/com.airhacks.afterburner.injection.PresenterFactory file. 

I think this might be useful for some situations, but I'd rather be able to specify this programmatically and have it locked down for my end clients.
