### ISSUE TITLE
How to use dagger2 as a dependency injection?

### ISSUE THREAD

**Issue by SaeedMasoumi** [AdamBien/afterburner.fx#59]
Hi,
Your Injector class uses `javax.inject`annotation and also dagger2 using the same one. 
So is it possible to ignore your injector and use dagger2 ?

**Comment by AdamBien** [comment]
Now it is: http://www.adam-bien.com/roller/abien/entry/afterburner_fx_v1_7_0 Thanks for filing this issue!
